### ISSUE TITLE
 [request] a few proposals for future version of Loudness Compensator plugin

### ISSUE THREAD

**Issue by capoei** [lsp-plugins/lsp-plugins#130]
1) considering that most of the time the volume knob is used it realy should be bigger then the others; like on amplifiers

2) the clipping part should be clearly separated imo

3) the status quo 1kHz reference tone at 0dBFS button doesn't realy make sense.
the "normal" procedure is using pink noise @ -20dB RMS. since the audio streaming portals now kind of set a new standard with their normalizing at around -14LUFS I personaly use pink noise at -14dB RMS.
if we add a LUFS/RMS meter we can "kill 2 birds with one stone". the reference button would be playing pink noise, adjustable via the input knob to level the system to the chosen LUFS level.
a button near the LUFS meter would adjust the 0 level.
if you manly listen to streaming portals you would adjust your system to read 83dB on SPL meter while the pink noise reads 0 at the K14 LUFS meter (-14RMS)
now, if you switch to a other source, like an 80ies CD you would adjust input gain to hover around +- 0 (+3 peaks) on the LUFS meter. this way all your music will have about -14LUFS (*)

![Screenshot_20200717_115915](https://user-images.githubusercontent.com/22452408/87802728-fb15a180-c827-11ea-9286-63a192ea37cf.png)

(*) LUFS is not perfect. percieved loudness will change between bass heavie and light bass material for example, but it is the best we have. the only other option is using ears

**Comment by capoei** [comment]
note that K20 also works for the traditional -20dB RMS pink noise calibration

**Comment by sadko4u** [comment]
I think I'll work on new meters after completely move to the 1.2.0 version and new build process.

So this feature will be a bit delayed.

Further releases will introduce plugins that don't change the core libraries significantly which won't make me frustrating by porting all the changes to other source code trees:
https://github.com/sadko4u/lsp-dsp-lib
https://github.com/sadko4u/lsp-runtime-lib
https://github.com/sadko4u/lsp-test-fw
https://github.com/sadko4u/lsp-r3d-glx-lib
https://github.com/sadko4u/lsp-r3d-base-lib
https://github.com/sadko4u/lsp-lltl-lib
https://github.com/sadko4u/lsp-common-lib
https://github.com/sadko4u/lsp-ws-lib
https://github.com/sadko4u/lsp-tk-lib

**Comment by capoei** [comment]
(remembring I am just proposing)

actualy the perfect solution for the volume knob would be an option to reduce the plugin window to show only the volume button.
I find myself having to open the window a lot, so I would prefer to have it "always on top". now the way it is it is too big to stay always on top.
now the overperfect solution would be a tray icon (with close to tray*) which would change volume with mouse wheel (though I suspect this would be a lot of programing work)

* I actualy miss close to tray with the impulse plugins also, which are always on in my system

**Comment by capoei** [comment]
over the time I will post my observations regarding loudness here. IMO this is a crucial for listening with loudness compensation. and btw, if you always listen to perfect balance, mixing songs into perfect balance will be automaticly.

atm I am listening to Spotify (metering with X42 LUFS meter). they actualy use Replay Gain, instead of LUFS normalization. It seams to work much better for the bass heavy vc light bass issue. bass heavy songs actualy peak much higher on the LUFS meter

**Comment by Mitchco** [comment]
Hello, any news on being able to use the Pink Noise procedure as described in point 3 from the OP? Thanks.

**Comment by sadko4u** [comment]
I think we are almost ready for implementing all the proposals now.

**Comment by Mitchco** [comment]
Wow, that is huge! There are so few implementations of loudness compensation, this will be most welcome! Thanks!

**Comment by capoei** [comment]
Mitchco from ASR? small world lol

**Comment by sadko4u** [comment]
So, we got additional LUFS meters in the UI and pink noise generator as a reference for set of levels: -23, -20, -18, -16, -14 and -12 LUFS. I think this is pretty enough. @bor-T will polish the UI.

**Comment by sadko4u** [comment]
Available in 1.2.18.
