### ISSUE TITLE
Swiss knife in graphic sound control.

### ISSUE THREAD

**Issue by bor-T** [lsp-plugins/lsp-plugins#165]
Hola, senior.
First of all, I want to say thank you for the plugins and for all work what u done.

LSP is a great plugin bundle. But what else I would like to see in the LSP. Actually a lot of things ))) But most of all, this.

Is it possible to make a plugin that will combine an analyzer, a spectrum analyzer, an oscillator, a goniometer, and maybe an rms and a k-meter, or some else graphic control of sound? Well, in general, such as a monster monitor, a multimeter or a Swiss knife in graphic sound control.

More detailed.
What I need it for. Total monitoring of the master channel, comparison of several tracks and not only.

Options.
The first appearance when you just opened the plugin. 
All graphs (what displays graphical information) are visible at once, each should have its own controls for tuning. Upside button what change the view.

When you press the button "change the view", second appearance is activated. The view change to view of graff in full size. At the top, buttons to switch between graphs (analyzer, a spectrum analyzer, an oscillator, a goniometer, rms and a k-meter).
Something like what, hope u understand idea.

If it is possible, to display additional information about the note in the analyzer, and the ability to see the signal level in relation to 0db.

So. In yours other plugins (such as the analyzer), you have implemented everything quite well (control buttons), so it makes no sense to describe each parameter.

Thank you in advance, and thank you again for the LSP.

p.s.
Maybe other users have similar ideas, or have ideas how we can do this plug with best functionality.

**Comment by sadko4u** [comment]
Implemented in 1.2.20!
