### ISSUE TITLE
[Bikeshedding] Parameters idiosyncrasies

### ISSUE THREAD

**Issue by LebedevRI** [lsp-plugins/lsp-plugins#265]
I'm not sure this is a problem in a wide reality, but it does seem limiting somewhat to me, so i thought i'd at least file it.

The issue is easy to summarize, and it's endemic to all of the parameters:
While ~all of the parameters can be set with a nice precision (2 decimal points usually),
all parameters have a, usually very strict, ranges.

Some examples:
* While `Reactivity` is can be set to a somewhat generous `250ms`, `Lookahead` is limited to `20ms`, Yet one can put `Delay Compensator` on the input (but *not* sidechannel), and get any lookahead.
* In `Delay Compensator`, `Delay` can be set to whopping `1000m`, yet the `Samples` can only be set to `10'000`, which is `~226.7ms` at `44.1kHz` but only `52ms` at `192kHz`...
* In `Dynamic Processor`, `Threshold`/`Gain` starts at `-72dB`. For example, if i want to keep any input, that does not lead to gate opening, at -72dB, i can do that, but any lower than that i need to play around with input gain/output gain/markup.
* Equalizer/filters only go up to ~20kHz. I suppose this is fine in most of the cases, but e.g. it gets somewhat limiting if you want to place low-pass somewhat higher than 20kHz, to have less attenuation of the 20kHz itself.

Any thoughts on this in general?
It's not really worth to adjust the specific things i pointed out by themselves, noted.

**Comment by sadko4u** [comment]
In many plugin formats each parameter has strict defined bounds.
I think there is no reason to synchronize the maximum value with the sample rate.
If you're feeling that some range is too small, you're welcome to suggest the extension of the parameter's range.

**Comment by LebedevRI** [comment]
Thank you for taking a look! This was *not* meant to hard-criticize LSP.

> In many plugin formats each parameter has strict defined bounds.

Yep, i have seen that, and that's precisely the pain point. It seems like
they should be *soft*, recommended, bounds, and it should be possible
to go outside of them. But that clearly won't play well with LSP's
rich graph displays, that also have specified ranges.

> If you're feeling that some range is too small, you're welcome to suggest the extension of the parameter's range.

Right. Sadly i haven't really encountered anything in particular that is sufficiently outrageous
to warrant looking into improving it, it's just that every once in a while //some// thing seem, arbitrary?

**Comment by sadko4u** [comment]
> they should be soft, recommended, bounds, and it should be possible

Sometimes it's not possible, especially when we're talking about the reallocation of some audio buffers at runtime.
That requires to call some memory allocation functions and breaks the RT compatibility of the DSP code.

> while //some// thing seem, arbitrary?

What do you mean under the term 'arbitrary'?

**Comment by LebedevRI** [comment]
> > they should be soft, recommended, bounds, and it should be possible
> 
> Sometimes it's not possible, especially when we're talking about the reallocation of some audio buffers at runtime. That requires to call some memory allocation functions and breaks the RT compatibility of the DSP code.

Note: i'm not familiar with LSP's sources.
Are required temporary memory buffers being allocated with constant fixed size
determined by the hardcoded bounds of the parameters?

> > while //some// thing seem, arbitrary?
> 
> What do you mean under the term 'arbitrary'?

In the sense that it's not really obvious why the particular range was chosen.
I think, overall, essentially, i'm missing better docs, that would also mention such things.

**Comment by sadko4u** [comment]
> Are required temporary memory buffers being allocated with constant fixed size
determined by the hardcoded bounds of the parameters?

Some buffers depend on the maximum parameter's value AND on the selected sample rate.

**Comment by LebedevRI** [comment]
Ok, after playing with LSP some more (directly, as opposed to using it through easyeffect)
in attempt to come up with some mic gating i'd like, i have a recurring issue with gain-like controls.

Constructively, would it be acceptable to **consistently**, **indiscriminately** change the limits
on input|output gain/markup/threshold/gain to go +/-`96`dB, as opposed to being +/-`60`/`72`/`???`dB?

**Comment by sadko4u** [comment]
Why do you need such low thresholds? Any application?

**Comment by sadko4u** [comment]
> Also, it would be nice to be able to select between operating in plain dB and (K-weighted) LUFS.

Do I right understand that you mean that you need to measure the input and output in LUFS?

**Comment by LebedevRI** [comment]
And another example: i'd like to see how some parameters of Equalizer are at low-pass filtering.
E.g., at which parameters there's still minimal fall-off at 20khz, but nothing above 22khz is passed.
For that, it is logical to use the Oscillator, except i can't set it to any frequency higher than 20khz...

**Comment by sadko4u** [comment]
> E.g., at which parameters there's still minimal fall-off at 20khz, but nothing above 22khz is passed.

What's the purpose? The fall-off is defined by the filter type. The most extereme one is LRX filter with a Q value slightly raised (if you don't need huge amplitude distortion).

> but nothing above 22khz is passed.

Because you are using 44.1 kHz sample rate and the 22.05 kHz is the Nyquist frequency? Or I don't understand your use case.

**Comment by LebedevRI** [comment]
> > but nothing above 22khz is passed.
> 
> Because you are using 44.1 kHz sample rate and the 22.05 kHz is the Nyquist frequency? Or I don't understand your use case.

Yes. Essentially, i was trying to see if i can mimic https://www.youtube.com/watch?v=-jCwIsT0X8M

**Comment by sadko4u** [comment]
@LebedevRI 
Is this thread still actual?

**Comment by LebedevRI** [comment]
I don't think anything changed here.
If nothing is going to be done about the issues noted above, feel free to just close this.

**Comment by sadko4u** [comment]
> While Reactivity is can be set to a somewhat generous 250ms, Lookahead is limited to 20ms, Yet one can put Delay Compensator on the input (but not sidechannel), and get any lookahead.

I don't see any purpose for setting long look-ahead time. In most cases the look-ahead time is designed to make dynamic device working a bit earlier. 20 ms is much larger time period than the peak of any kick drum, so I don't see any necessity to widen this parameter.

> In Delay Compensator, Delay can be set to whopping 1000m, yet the Samples can only be set to 10'000, which is ~226.7ms at 44.1kHz but only 52ms at 192kHz...

If you use sample-precition correction, then you probably don't need large delays. Large delays are added for users that use the Delay Compensator for some other purposes rather than phasing different microphones or instruments. You just can switch to another units and set the larger delay value.

> In Dynamic Processor, Threshold/Gain starts at -72dB. For example, if i want to keep any input, that does not lead to gate opening, at -72dB, i can do that, but any lower than that i need to play around with input gain/output gain/markup.

For such extreme values yes, you need to drive in the sidechain preamp knob. It is also designed for such purposes. If we widen the threshold, we are forced to draw the curve graph including these values. This will make the final graph more messy, less detailed and harder to understand.

> Equalizer/filters only go up to ~20kHz. I suppose this is fine in most of the cases, but e.g. it gets somewhat limiting if you want to place low-pass somewhat higher than 20kHz, to have less attenuation of the 20kHz itself.

With 44100 kHz or 48000 kHz sample rate it is impossible to process audio above the nyquist frequency which will be repectively 22050 and 24000 kHz. Additionally, very rare people hear anything above 16 kHz, so I think it is a pretty fair high boundary of the frequency range.
