### ISSUE TITLE
Feature request: mix control (or link Wet and Dry controls)

### ISSUE THREAD

**Issue by lrfinotti** [lsp-plugins/lsp-plugins#287]
On the compressor plugins (and maybe others, such as IRs) it would be nice if there were a single mix knob, besides the independent Wet and Dry knobs.  It would make much easier to hear the Wet/Dry blend, as we can only turn one know at a time with the mouse.  (Right now we turn one down, the other up and try to match the loudness.  At that point my ear already lost reference of how it sounded before.)

Or, perhaps have a "link" selector between then Wet and Dry, so that turning one up turns the other down by the same amount.  (I am not sure if that is exactly the same as mix knob or if there is more to it than that...)

**Comment by sadko4u** [comment]
Hello!
Two-knob control is much more flexible. I mean, you can separately control the amount of dry and wet signal.
When using the Mix control, we should assume that the level of the dry signal should be 0 db and the level of the wet signal should be -inf dB at the leftmost position and vice verse at the rightmost position. But there is actually no idea what to do if you previously have set up the dry and wet values to your custom value. Probably changing the operating mode and replacing two single knobs with one knob by some switch should do the job.

**Comment by jean-emmanuel** [comment]
That would be awesome !

**Comment by sadko4u** [comment]
What's the main purpose of this feature? Do you use the `Mix` control for A/B testing?
For A/B testing you can use the Bypass button which is pretty fine with it.
At this moment I don't see any good way to combine the 'Dry', 'Wet' and 'Dry/Wet' balance without introducing mode switch button which is unwelcome.

**Comment by lrfinotti** [comment]
The idea would be to hear changes in small steps, in a continuous way.  Slowly going from Wet to Dry you can hear how compression is affecting the sound and find a sweet spot.  

Also, it (more or less) matches the levels.  With two hands on knobs, you can turn the dry knob up and the wet down at the same time to match the volume as you listen, but it is impossible with a single mouse.

An alternative would be to have a "link" button to link the wet and dry volumes. so that turning one knob up by, say, 1dB, turns the other down by the same amount (like 1dB as well).

But, of course, I understand if there is no good way to implement it.

In any event, thanks for your consideration!

**Comment by sadko4u** [comment]
Finally, we came to such solution: just implement additional Dry/Wet knob, where the final signal flow will be the following:

![изображение](https://github.com/lsp-plugins/lsp-plugins/assets/12834464/31300fb0-a732-41e4-a736-5fc0d0b5e76d)

This allows to keep the previous behaviour when `DryWet` is set to `100%` and control the Dry/Wet balance when setting `Dry=-inf dB` and `Wet = 0 dB`.

In 1.2.15 release, the knob will be available for all dynamic processing plugins.

**Comment by sadko4u** [comment]
Fully available in 1.2.16!

**Comment by cyrusadkisson** [comment]
I'm sorry, this makes no sense at all. If you turn dry/wet to 100% wet, you should hear no dry. And currently I do. Any UI programmed to not function this way is objectively incorrect.

**Comment by sadko4u** [comment]
It behaves as it is designed on the diagram. We already have had separate Dry and Wet controls and designed such schema to make the update compatible to already existing user projects. You may agree or not but it is designed for backward compatibility and works as documented here.

**Comment by cyrusadkisson** [comment]
Why would turning dry/wet to 100% wet let any dry through? Do you realize that is completely unintuitive?

**Comment by sadko4u** [comment]
Consider the 'Dry/Wet' knob being a knob that controls the balance between Dry signal and Mix of Dry/Wet.
The same is written in documentation:
* Dry/Wet - the balance between unprocessed (Dry) signal and mixed signal (see Dry and Wet controls).
