### ISSUE TITLE
Maximum value in meters

### ISSUE THREAD

**Issue by bor-T** [lsp-plugins/lsp-plugins#304]
Hola. For ease of operation with input and output volume levels, we should add to the meters a selection of the maximum value, which will be reset when you click on it.

![iss_meter](https://user-images.githubusercontent.com/75978208/220264347-002b7bf4-44b3-42e4-b838-3b5235e0f2a0.png)

**Comment by sadko4u** [comment]
Added possibility to enable maximum value tracking by additional option `header.visible` to the `<ledmeter>` tag. Here is the example:
```xml
<!-- Output signal meter -->
<ledmeter vexpand="true" height.min="256" angle="1" header.visible="true">
	<ledchannel id="olm_l" min="-72 db" max="24 db" log="true" type="rms_peak" peak.visibility="true" value.color="left"/>
	<ledchannel id="olm_r" min="-72 db" max="24 db" log="true" type="rms_peak" peak.visibility="true" value.color="right"/>
</ledmeter>
```

**Comment by sadko4u** [comment]
Added support by the plugin framework in 1.2.17.
