### ISSUE TITLE
plugin request > gain match

### ISSUE THREAD

**Issue by sdfsfsfwrt** [lsp-plugins/lsp-plugins#323]
two plugin one of them insert in begin and end of channel strip or before and after a plugin 
first one receive  gain and  second  one adjust gain to match with first plugin input 
this two plugin are linked together for matching gain

**Comment by sdfsfsfwrt** [comment]
Hello 
Help to keep gain staging state entire channel strip - 
put plugin between gain match plugins  - more control on input and output of a plugins
however in mixing some time regular digital level is very hot for a analog gear or analog modeled plugin
this plugin help to stage gain before run to them 
and match before and after distortion like plugins because them add gain to signal and we as human always say louder is better - simply this plugin f*ck **" loud is better "** philosophy  
specially in mastering processes it help engineer to easy hear plugins and gears
often in compressing it help to hear compressor correctly because input and output are same 
and +/- gain cant affect on producer decisions  because producer compress in isolate space (between 2 gain match plugin)

and this plugins can have some option 
automatic gain stage
manual gain stage 
gain stage with rms/peak
and inline display in ardour when level match second plugin e.g light green when level get match with first one

**Comment by sadko4u** [comment]
I think adding basic frequency weightening functions (A, B, C, D, K) is also very important since our ear perceives different frequencies in different way.
The idea of such plugin is interesing. I think it is a good point to go for 1.2.10 release.

**Comment by sdfsfsfwrt** [comment]
more idea

phase relationship checker between first and second plugin 
compare input/output  and give graph to user - useful to analyze what plugin/s do 
reverse gain ; increase gain of second plugin automatically reduce gain from first one 

maybe increase your creativity

**Comment by sadko4u** [comment]
Partially implemented in the Autogain tool (sidechain version).

**Comment by sadko4u** [comment]
Finally, all functions available in 1.2.18 using the Send plugin in combination with Autogain.
