### ISSUE TITLE
Editable labels for mixers ?

### ISSUE THREAD

**Issue by ssabug** [lsp-plugins/lsp-plugins#355]
Hello,

First thank you for providing these plugins, their quality sets the bar so high they're IMO must have in a linux audio environment.

I was wondering if we can expect to have in the future editable labels for each track in mixer plugins? 
For the moment we just have static names with #.

Having the ability to set a custom text label would be a really interesting feature.
Adding to this a selectable color for the text/track header would also be very nice.

**Comment by sadko4u** [comment]
Hello! Pretty interesting and usable feature.

**Comment by sadko4u** [comment]
Available in 1.2.15
