### ISSUE TITLE
Revert default zoom level to previous (Filter, Graphic Equalizer, and Parametric Equalizer)

### ISSUE THREAD

**Issue by p-chan5** [lsp-plugins/lsp-plugins#368]
The previous value (0.00 dB) allowed for a broader overview of the frequency spectrum. Now with the new value (-36.00 dB) the audio loses great detail (when I work at -10.00 LUFS).

Zoom at -36.00 dB (default value):

![001](https://github.com/lsp-plugins/lsp-plugins/assets/123143444/96057be4-2717-4356-8000-9c417c49b8cb)

Zoom at 0.00 dB (previous default value):

![002](https://github.com/lsp-plugins/lsp-plugins/assets/123143444/c5cba154-d6a5-4aa7-88d5-05baa2268704)

**Comment by sadko4u** [comment]
You can disable spectrum scaling by `Menu` -> `UI Behavior` -> `Automatic frequency graph scaling`. After that, the `Zoom` fader won't affect the spectrum graph.

**Comment by sadko4u** [comment]
@p-chan5 is the problem solved for you?

**Comment by p-chan5** [comment]
Yes, I disabled that option and it seems to be working fine, thank you very much for your time <3
