### ISSUE TITLE
Spectrum Analyzer - Grid color and visibility

### ISSUE THREAD

**Issue by ben0815** [lsp-plugins/lsp-plugins#371]
Is it possible to change the color and visibility of the grid?
Because in the Spectralizer mode, the color of the signal is the same as the grid, so its nearly impossible to see/detect the frequency.

**Comment by sadko4u** [comment]
Hello! Could you please add screenshot that describes your problem?

**Comment by ben0815** [comment]
![Spectralizer_01](https://github.com/lsp-plugins/lsp-plugins/assets/46386358/1b34af43-2e42-4854-959b-91f880ec9fac)
I used red, maybe that's not a good choice in live performance. But it proofs the point. It's very hard to detect the frequencys in a live event (feedback detection) to adjust the frequence on the live console eq.
So the question: is it possible to have a value to select a color for the grid and maybe the thickness of the grid lines?

**Comment by sadko4u** [comment]
I think we need to ask @bor-T . Any ideas of how to improve the grid experience?

**Comment by sadko4u** [comment]
You also can play with different modes of spectralizer data presentation. This also may be useful.

**Comment by ben0815** [comment]
Thank you for the answers.
I tried other modes, changed the preamp and/or shift values, but didn't really help.

**Comment by ben0815** [comment]
Any ideas, how to add a field for the color and thickness of the grid?

**Comment by sadko4u** [comment]
We're thinking on changing the order of drawing grid lines and the framebuffer data.

**Comment by bor-T** [comment]
> Any ideas, how to add a field for the color and thickness of the grid?
In next release it will be looks like this.
![spectrum](https://github.com/lsp-plugins/lsp-plugins/assets/75978208/11e1489d-31b3-4ba9-bb2c-924492be3be8)

https://github.com/lsp-plugins/lsp-plugins/assets/75978208/360c0a4b-1dd6-45e3-9842-87b9844a07f4

**Comment by ben0815** [comment]
Wow!
Thank you very much! That will really help!

**Comment by sadko4u** [comment]
Available in 1.2.15.
