### ISSUE TITLE
Resizing, just dosent work as expected on a hybrid laptop

### ISSUE THREAD

**Issue by HerrSnorre** [lsp-plugins/lsp-plugins#374]
Note: my ingles teacher hates me (im doing my best with a translator)

> "Did you use the previous version of plugins? If yes, did they properly work and have you properly uninstalled the previous version?"
  - I knew this issue for a long time, but now it kinda worse (nvidia problem?)
  
> "What version of plugins caused a crash?"
  - I am using the latest that pacman (archlinux) has, and i keep it up to date

> "Was it LV2, LinuxVST, LADSPA or standalone package?"
  - Standalone, i usualy use carla, but it crashes with another plugins

> What CPU and memory configuration do you use? This can be done by issuing 'cat /proc/cpuinfo' and 'free' commands.
  - 10th gen Intel core I5 (overclocked from factory, 0.8Ghz - 4.5Ghz / 2.5Ghz base)
  - 16Gb RAM (6Gb free)
  - Nvidia GTX 1650 Mobile
  
> "What Linux distribution do you use? This may be done by issuing 'uname -a' and 'cat /etc/issue' commands."
  - Arch Linux x86_64
  - Kernel: 6.7.0-arch3-1
  - Nvidia driver: nvidia-open-dkms 545.29.06-13

> "What version of required (see 'INSTALLATION') packages are present in your system?"
  - I didn't found 'INSTALLATION'

> "Provide the full list (besides LSP Plugins) of plugins that you used in your host."
  - Calf (on CalfJackHost) (Bass enchancer, Exciter, Stereo Tools, Multiband Limiter)

The real problem
![LSP](https://github.com/lsp-plugins/lsp-plugins/assets/79027813/fbe21303-020e-4532-871a-6a22ab4ac5ad)

![LSP](https://github.com/lsp-plugins/lsp-plugins/assets/79027813/5fb85a2e-1911-4b62-9136-3b041f946784)

(Is this a wayland issue?)

**Comment by sadko4u** [comment]
Hello! Looks very strange. Never issued such problem before.
This also may be a bug in a driver. Did you try the standalone version on X11-based desktop of your PC?

**Comment by HerrSnorre** [comment]
I noticed that some programs on xwayland are kinda broken when resized.
But still, lsp shows some white and transparent lines, Brave (for example) shows a wierd shadow with the bgcolor of the page opened, it only apears while resizing.
Every wayland native looks fine.

On firefox, this dosent happen

![image](https://github.com/lsp-plugins/lsp-plugins/assets/79027813/2ad3545d-9fe6-4617-92d7-f2ca216b1aa0)

Maybe a xwayland bug?

**Comment by sadko4u** [comment]
LSP uses entire window buffer to draw widgets on it by issuing `cairo_xlib_surface_create` and `cairo_xlib_surface_set_size`. Maybe it is somehow not properly emulated by the xwayland.
Anyway, we don't guarantee proper work of UI on Wayland at this moment. The better solution could be to just add support of wayland protocol but we don't have time for it at this moment.

**Comment by HerrSnorre** [comment]
Makes sense
Maybe x11 is a better option for now

Thx for the info
