### ISSUE TITLE
12 db/oct slope for Crossover

### ISSUE THREAD

**Issue by atskler** [lsp-plugins/lsp-plugins#379]
Dear sadko4u,

I would like to ask if you could implement a 12 dB/oct slope option for your Crossover plugins.
This would be helpful for a more gentle multiban processing with compressors. (This slope is used in some multi-band broadcast processors.)

Thank you for considering this,

A.

**Comment by sadko4u** [comment]
Hello! The support of LR2 (12 dB/oct) filter will be available in 1.2.15.

**Comment by atskler** [comment]
> Hello! The support of LR2 (12 dB/oct) filter will be available in 1.2.15.

Thank You, sadko4u! 🙏

**Comment by atskler** [comment]
Dear sadko4u,

I just tried the devel version with the LR2 (12 dB/oct) filter and in the Classic mode there seems to be some phase issues between the bands. For example if I use the default 4 bands then I had to apply the "phase" function for the 2nd and the 4th band for correct summed sound.

The LR 4-8-12-16 filters are correct in Classic mode.
The Liner Phase mode is correct with LR2.

Could you please check this?

Thank you in advance,

A.

**Comment by sadko4u** [comment]
Hello! Ok, seems that I need to correct allpass filters.

**Comment by sadko4u** [comment]
Just committed update. Please check

**Comment by sadko4u** [comment]
Nice

**Comment by sadko4u** [comment]
Available in 1.2.15.

**Comment by atskler** [comment]
Thank You, sadko4u! 🙏

**Comment by atskler** [comment]
Dear sadko4u,

I would like to ask if you could also implement a 6dB/oct and a 18dB/oct slope for the Crossover plugin?
(Here again I ask this for finding the sweet spot for multi-band compression schemes.)

Thank you in advance for considering this,

Attila
