### ISSUE TITLE
Crossover plugin Solo & Mute functions

### ISSUE THREAD

**Issue by atskler** [lsp-plugins/lsp-plugins#381]
Dear sadko4u,

Currently the Solo/Mute functions just enables soloing/muting of the corresponding frequency band for the monitoring channel. Could you implement a way to do this for the actual separate output channels?

For example for setting up a multiban compression scheme I would like to solo one band and listen to just that for adjusting the compression on it. Then I would like to do this for the next channel. Then I would like to hear for example two chosen channels from five through their respective compressors.

Thank you in advance for considering this,

A.

**Comment by sadko4u** [comment]
I think the best solution could be implementation of a separate button that reflects the state of the monitoring channel to band outputs. This allows to control monitoring section only or both monitoring and channel output.
What do you think?

**Comment by atskler** [comment]
Sounds good to me.
Thank you for working on it.

**Comment by sadko4u** [comment]
Introduced `S/M Apply` button for Crossover plugin series.

**Comment by atskler** [comment]
Thank You! 🙏
Works excellently.

**Comment by sadko4u** [comment]
Available in 1.2.15.
