### ISSUE TITLE
Carla for Windows cannot load LSP VST3s correctly.

### ISSUE THREAD

**Issue by Lowclock** [lsp-plugins/lsp-plugins#384]
Tried building everything with the latest MinGW-W64, PHP, GNUmake, etc and it seemed to go just fine. Everything shows up and is functional in Audacity, except for those requiring file loading like Impulse Responses/Reverb. In Carla, however, all the plugins are discovered, but trying to actually load any of them just results in the console being flooded with

`[WRN] Non-existing client=0000000004CCED88`

and eventually just loading the first visible plugin, A/B Tester x2 Mono. The UI is offset as noted in #383, but doesn't cause any crashes in Audacity or Carla.

GNU Make 4.4
MinGW-W64 8.1.0
PHP 8.3.3
Carla 2.5.8
LSP 1.2.15
Windows 10 Pro, Ryzen 3700x

**Comment by sadko4u** [comment]
It seems that multi-plugin VST3 is not supported by Carla at this moment.
I'm trying to instantiate any plugin but it always tries to instantiate the first one in the list of the factory.
@falktx please give more information.

**Comment by falkTX** [comment]
the feature is just not implemented yet, mainly due to me not really seeing any plugins making use of it. yours are the first that I know that use this extensively.

**Comment by sadko4u** [comment]
@falktx it seems now you have examples to experiment with :)

**Comment by Lowclock** [comment]
> the feature is just not implemented yet, mainly due to me not really seeing any plugins making use of it. yours are the first that I know that use this extensively.

All of the [Waves](https://www.waves.com/) VST3 plugins also have the same problem.

**Comment by sadko4u** [comment]
Closing the issue as it is the problem of the Carla host.
