### ISSUE TITLE
Multisampler, wrong path stored inside cfg file

### ISSUE THREAD

**Issue by Daniele71** [lsp-plugins/lsp-plugins#390]
Hi, not sure if it's really wrong but... I was trying to retrive a full path of a sample, then I opened the cfg file that i made month ago. With big surprise, all samples path are pointing to my /home/$user/Ardour_Sessions/$session_name/plugins/59925/state14/$sample_name.
$sample_name is a symlink to Ardour externals dir where $sample_name is another symlink to real sample.

Is this correct ? I'm sure that I already did this operation in the past  and there was the real path.

lsp-plugin 1.2.15 lv2 from proaudio repo on openSUSE TW

Thanks.

**Comment by sadko4u** [comment]
Hello!
LSP Plugins use [LV2 mapPath](https://lv2plug.in/ns/ext/state#mapPath) feature which is required for making sessions portable between computers. The responsibility of creating symbolinc links or files is delegate to the host application.

When the LV2 plugin saves the state, it is required to call `abstract_path` function to make the DAW do the usual job. When the plugin restores the state from the session, it uses the path the DAW returns to it when calling the `absolute_path` function.

Please consider looking following threads:
https://github.com/lsp-plugins/lsp-plugins/issues/386
https://github.com/lsp-plugins/lsp-plugins/issues/119
https://github.com/lsp-plugins/lsp-plugins/issues/118
https://github.com/lsp-plugins/lsp-plugins/issues/132

**Comment by Daniele71** [comment]
I don't know...  cfg file should stay with full path to sample. What if I delete the the ardour session dir and move to another DAW ? All my custom kit become trash ?!? This is wrong, IMHO.

**Comment by sadko4u** [comment]
OK, this is reasonable.

**Comment by Daniele71** [comment]
Thanks !

**Comment by sadko4u** [comment]
I've just committed changes to `devel` branches of all affected sub-projects and tested. Now the path provided by Ardour is properly converted to the path to the original file. You can build from `devel` branch and verify.

**Comment by sadko4u** [comment]
Fixed in 1.2.16!
