### ISSUE TITLE
Slapback Delay: Add Feedback

### ISSUE THREAD

**Issue by Bleuzen** [lsp-plugins/lsp-plugins#391]
Hi, thanks for the plugins :)
Would be pretty cool if you can add a Feedback knob (one per delay line) to the Slapback Delay plugin, for example next to the Gain knob:

![](https://github.com/lsp-plugins/lsp-plugins/assets/12885163/ac5c9c8e-31ea-475e-8c03-6e4a59a88e29)

**Comment by Bleuzen** [comment]
@sadko4u I see you added it and I'm excited for the next release, cool :)

I left a small donation, hope it reached you.
Had to use Patreon as a workaround because Paypal says I can't send you money (doesn't give a specific reason) and Liberapay says "Cannot be renewed because the account of the recipient isn't ready to receive new payments."

Also I usually would prefer one-time donations
found https://ko-fi.com/ which seems to provide this, might be worth looking into it if you want

**Comment by sadko4u** [comment]
@Bleuzen 
Hello! Thank you for donation. Sad, but PayPal stopped any financial exchange with russian citizens due to sanctions, so now I have very few options to receive donations.

The new release will be soon.
