### ISSUE TITLE
GUI bug with Slapback Delay Mono

### ISSUE THREAD

**Issue by Houston4444** [lsp-plugins/lsp-plugins#394]
Hi.

There is a little bug in Slapback Delay, in a delay line, if I set mode to notes, and I set delay numerator to 1, then set denominator to 8, (1/8), denominator comes back to 4 and numerator to 0 (0/4). So, the only way to got a 1/8 measure delay is to set manually fraction to 0.125.

Note that, if I change the denominator to 8 in a generic UI (here with Carla plugin parameters), the denominator changes correctly in GUI.

Edit:
The bug seems to only appears in the LV2 GUI, not in the VST one.

**Comment by sadko4u** [comment]
Hello! Not reproducible for me. What host do you use?

**Comment by Houston4444** [comment]
I use Carla 2.5.8.

If it was not very clear, here is a short video example (sorry for the french interface):

https://github.com/lsp-plugins/lsp-plugins/assets/3808689/688989f2-a847-4ee5-b88f-6ddddf6ce84a

**Comment by sadko4u** [comment]
Yes, can confirm that it is reproducible for Carla. I don't have such behaviour in Ardour, need to test.

**Comment by sadko4u** [comment]
Fixed the problem. Should be available in the next release.

**Comment by Houston4444** [comment]
Nice, congratulations!

**Comment by sadko4u** [comment]
Fixed in 1.2.16!
