### ISSUE TITLE
Filter: another ear-damage bug

### ISSUE THREAD

**Issue by LebedevRI** [lsp-plugins/lsp-plugins#395]
Try setting frequency of high-pass filter to below ~20 Hz:
![image](https://github.com/lsp-plugins/lsp-plugins/assets/88600/119eb821-5ec3-4ddb-b355-8f092c681cef)

This is with lsp-plugins 1.2.15-2 on debian sid.

**Comment by sadko4u** [comment]
Works for me. What should happen?

![изображение](https://github.com/lsp-plugins/lsp-plugins/assets/12834464/a4a11b81-307e-4b27-a1c8-468daf980fc9)

**Comment by sadko4u** [comment]
I see parasite low frequencies at the cutoff frequency:
![изображение](https://github.com/lsp-plugins/lsp-plugins/assets/12834464/4fa34979-d97c-4e3b-88f5-fd10e1b91631)

I suppose this is related to floating-point rounding errors or to very aggressive phase jump.

**Comment by LebedevRI** [comment]
The observable effect is quite similar to that of https://github.com/lsp-plugins/lsp-plugins/issues/380
Look at the output levels:

https://github.com/lsp-plugins/lsp-plugins/assets/88600/7e525d8c-d291-49b5-a663-b34e562f34b8

**Comment by sadko4u** [comment]
I don't see such behaviour on my machine.
Need more detailed information about CPU (/proc/cpuinfo) and your audio settings.

**Comment by LebedevRI** [comment]
That's 

> Need more detailed information about CPU (/proc/cpuinfo)

This is `AMD Ryzen 9 5950X`, so i guess AVX2 codepath is being used.

> and your audio settings.

Same as in #380. This reproduces *very* reliably in both EE and carla,
both during normal usage, and in that synthetic test i've shown...

Please let me know if that is insufficient amount of information.

**Comment by sadko4u** [comment]
I also run plugin on AMD CPU (4800H). What's your sample rate and audio buffer size? I think this may be related.

**Comment by LebedevRI** [comment]
192k/8192, same as in #380.

**Comment by sadko4u** [comment]
Looks like really floating-point rounding errors. Changed `float` to `double` in bilinear transform function, and this solved the problem:
https://github.com/lsp-plugins/lsp-dsp-units/commit/c7616b3ef8d7076750c5a27444bfef025d3be62a

**Comment by LebedevRI** [comment]
@sadko4u thank you for taking a look!

**Comment by sadko4u** [comment]
Fixed in 1.2.16!
