### ISSUE TITLE
jumping ui because of numbers

### ISSUE THREAD

**Issue by atskler** [lsp-plugins/lsp-plugins#397]
Depending on the length of the displayed numbers the ui jumps left  and right.
This is how it looks like on video:
https://www.dropbox.com/scl/fi/5lalyo1h4an8iufy6k644/lsp_ui_jump.mp4?rlkey=q4ypn6n21vuwvyxzftoj9en0u&st=5yqe425j&dl=0

**Comment by sadko4u** [comment]
Hello! Did you adjust font scaling?

**Comment by atskler** [comment]
Hello!
Yes, "Force font DPI: 133" is set in KDE. Global scale is set to 100%.

**Comment by sadko4u** [comment]
Ok. Seems that I found solution for any font size by estimating the size parameters of the `Label` widget as maximum size of different kinds of value: minimum allowed, maximum allowed, default and special (like inf).
Will be available in the next release.

**Comment by sadko4u** [comment]
Available in 1.2.16!
