### ISSUE TITLE
VST3 Linux graph animations not working sometimes.

### ISSUE THREAD

**Issue by Stazed** [lsp-plugins/lsp-plugins#406]
Using LSP built from latest github.

Hosts: Qtractor and non-mixer-xt (https://github.com/Stazed/non-mixer-xt.git)

To reproduce, add various VST3 plugins with graph display to a Qtractor track or non-mixer-xt strip and process some audio.

Video for Graphic Equalizer. Top is VST3 and bottom is VST2, processing the same audio in non-mixer-xt.

https://github.com/lsp-plugins/lsp-plugins/assets/10453273/85d908dc-7c39-4030-a60c-010ff05ce20f

Screenshot for MB Dynamic Processor MONO. Left is LV2, right is VST3.
![Screenshot_2024-07-06_17-23-49](https://github.com/lsp-plugins/lsp-plugins/assets/10453273/9fba7e0c-d0b6-442c-a160-351a0c237d7f)

This only seems to effect some VST3 plugins with graph display.
(Equalizer, Parametric, MB Dynamic Processor Mono, Crossover, Beat Breather), were the ones that I tested.

The Crossover plugins show the FFT animations but do not show the Crossover lines.
The Beat Breather Mono does not show the Gain line.
The Beat Breathe Stereo does show the Gain line but it does not respond to changes to the gain dial.
The MB Dynamic Processor MONO - see screenshot.
The MB Dynamic Processor Stereo shows FFT animations but the Ratio low dial does not respond.

LV2, CLAP, VST2 all display correctly in both hosts.

Let me know if you need additional information or testing.

Thanks

**Comment by sadko4u** [comment]
Hello!

LSP Plugins uses VST3 Messaging mechanism to transfer data between the Processor and Controller.
If the host doesn't properly support VST3 messaging, it may be the reason why you don't see graphs or the behaviour of the UI is strange.

We already have had an issue where VST3 messaging caused memory leaks on Bitwig Studio here: https://github.com/lsp-plugins/lsp-plugins/issues/383

Anyway, I think I need to make a debug build and try to reproduce the case.

**Comment by Stazed** [comment]
This was caused by an incorrect Vst::TChar string size calculation in the mixer Vst::IAttributeList setString function.
Apologies for the noise!
Closing.

**Comment by sadko4u** [comment]
Nice!
