### ISSUE TITLE
VST3 Linux file handling/DND not working.

### ISSUE THREAD

**Issue by Stazed** [lsp-plugins/lsp-plugins#407]
Using LSP built from latest github.

Hosts: Qtractor and non-mixer-xt (https://github.com/Stazed/non-mixer-xt.git)

To reproduce, add VST3 LSP Impulse Responses to Qtractor track or non-mixer-xt strip and try DND or file loading of any impulse file. The file will not load.

File loading  works for other plugin types CLAP, LV2, VST2 in both above hosts.

**Comment by sadko4u** [comment]
The difference between the LV2, VST2, CLAP and VST3 one is almost nothnig. All use the same principle: provide an X11 window ID to build-in into some wrapper window. The problem can be related to the host that doesn't introduce XDnDProxy support for the plugin window.

**Comment by Stazed** [comment]
Apologies, I was not very clear and after further testing I found that **Qtractor** DND and browser file loading does not seem to work consistently.

So to clarify, for  **non-mixer-xt**, when using KDE Plasma desktop, both DND and file loading using the LSP file browser work without errors for LV2, CLAP and VST2. With VST3, neither DND nor file loading from the LSP file browser will load.

Below are the plugins that were tested with non-mixer-xt and all the plugins work with DND and using LSP file handler for LV2, CLAP, VST2 with KDE Plasma desktop. For XFCE desktop the DND does not work (as expected) but the LSP file handler does work and load files.

For VST3:
**Multi-Sampler X12 DirectOut**   - NO DND nor File Handler loading works
**Multi-Sampler x12 Stereo**  - No DND nor File Handler  loading works
**Multi-Sampler x24 Stereo**   - No DND nor File Handler  loading works
**Multi-Sampler x48 Stereo**   - No DND nor File Handler  loading works

**Impulse Response Mono**:
DND sometimes works with KDE Plasma, File Handler works sometimes.
Will generate an "unknown error" message when it does not work and then will not
load from DND or File Handler after error. The files that generate the "unknown error" message
will load for CLAP, LV2, VST2 plugins.

**Impulse Response Stereo** - Neither DND nor File Handler loading work. 
**Impulse Reverb Mono** - Neither DND nor File Handler loading work.
**Impulse Reverb Stereo** - Neither DND nor File Handler loading work.

Thanks

**Comment by sadko4u** [comment]
Do you see the file selector dialog when loading file?
Path parameters (which actually are files) are also implemented as VST3 Messages. Maybe this is also related to that case that Non Mixer does not properly transfer messages between the VST3 Controller and VST3 Processor?

**Comment by sadko4u** [comment]
Please consider this part of documentation: 
Here's the description about how Vst::IMessage should work:
https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/API+Documentation/Index.html#communication-between-the-components

**Comment by Stazed** [comment]
> Do you see the file selector dialog when loading file?

Yes, you can browse and select a file, but when selecting 'Open', the file does not load as with other plugin types.
I will look through the Vst::IMessage link to see if there is anything that looks wrong on my end.

FYI, the only other linux VST3 that I found that used DND and file browser, is **Wavetable** by socalabs:
https://socalabs.com and  DND and file browser work with it.

**Comment by sadko4u** [comment]
@Stazed the **Wavetable** can be implemented as a combined processor + controller + view solution into a single class. That's why it can have direct access to graphics and internal parameters of plugin.
According to VST3 specification, the right way of implementing data exchange between processor and controller is to use messaging or new data exchange mechanism based on buffers. It is justified with that fact that DSP and controller parts can run on different hosts, and we don't have direct access from controller to processor in this case.

**Comment by Stazed** [comment]
OK, found the issue!
This was caused by an incorrect Vst::TChar string size calculation in the mixer Vst::IAttributeList setString function.
This was also the problem with the display issues indicated in issue #406.

Thanks for pointing me in the right direction!
Closing.

**Comment by sadko4u** [comment]
Nice!
