### ISSUE TITLE
Building without X11 (some success already)

### ISSUE THREAD

**Issue by Ella-0** [lsp-plugins/lsp-plugins#412]
I've have been successful in getting this project to build without X11 for use in the audio stack on Apple Silicon machines running Linux distributions not shipping X11 software with some very hacky changes. I'd happily create a more upstreamable version of these changes however I'm struggling to understand how to efficiently commit identical changes to makefiles across many different repositories.

The rough idea I have for making X11 optional is making `lv2ui` a separate feature from `lv2` and when building `lv2` only without `lv2ui` X11 is not required.

I'm wondering how I should approach this.

**Comment by sadko4u** [comment]
Hello!

I think you can publish several PRs to several projects. The main idea is to move from the simple modules to more complicated ones, and the order looks like this:
- lsp-test-fw
- lsp-common-lib
- lsp-dsp-lib
- lsp-lltl-lib
- lsp-runtime-lib
- lsp-dsp-units
- lsp-ws-lib
- lsp-tk-lib
- lsp-plugin-fw
- lsp-plugins

If you publish the makefile changes for `lsp-common-lib`, I can propagate them to all other projects. I use special scripts for that purpose which automates the deploy of the changes among makefiles.

Please note that the target branch for the PR is `devel` (development branch), not `master`.
How do you look towards such plan?

**Comment by Ella-0** [comment]
I should only need to make changes directly to two repositories then: `lsp-plugins` and `lsp-plugin-fw`. How can I make the build system use the devel version of lsp-plugin-fw?

**Comment by sadko4u** [comment]
You can just checkout the `devel` branch in the main `lsp-plugins` repository and issue usual commands:
```
make config
make fetch
```

This will update all modules in the `modules` subdirectory to the `devel` branch.

**Comment by Ella-0** [comment]
Created merge requests #413 and https://github.com/lsp-plugins/lsp-plugin-fw/pull/5

**Comment by sadko4u** [comment]
The idea with additional `$(UI)` variable looks not very good. Instead of this, we have a `FEATURES` variable with enumeration of enabled features. We can define the `ui` feature which enables the UI for all enabled plugin formats.
I'm reviewing and refactoring the code in a new branch here:

https://github.com/lsp-plugins/lsp-plugin-fw/tree/noui-feature

Please wait a while until I get all formats working properly without the UI. At this moment' I'm, already done with CLAP format. There are still left JACK, VST2, VST3, and LV2.

**Comment by sadko4u** [comment]
I finished changes on the plugin framework. Here are commits:

https://github.com/lsp-plugins/lsp-plugin-fw/commit/00100010885a5bb2d7884b99a337dc0ffdeb804f
https://github.com/lsp-plugins/lsp-plugins/commit/ca7ea9983a3508c08d76ae7c6beb3d07608d43bf

You can try the development branch now. If we omit the `ui` option, all plugin formats will be built without UI support.

**Comment by sadko4u** [comment]
Good point. Added changes to the README.md

**Comment by sadko4u** [comment]
Available in 1.2.17.
