### ISSUE TITLE
VST3 [WRN] Non-existing client=xxxxxx messages

### ISSUE THREAD

**Issue by Stazed** [lsp-plugins/lsp-plugins#414]
Get about 4 of the above [WRN] Non-existing client=xxxx each time a VST3 is deleted. Seems harmless, but should it be something to worry about? Getting spammed on plugin scan... If harmless, could it be removed on release versions?
Otherwise, the VST3s are now working great in the mixer!
Thanks.

**Comment by sadko4u** [comment]
Removed this warning as non-fatal. The destruction process can issue multiple `unregister_data_sync()` calls and it is normal behaviour.

**Comment by sadko4u** [comment]
Fixed in 1.2.17.
