### ISSUE TITLE
Windows Build not working

### ISSUE THREAD

**Issue by ReComplexed** [lsp-plugins/lsp-plugins#417]
Hi,
I have a real problem with trying to build the Windows version. I have made all my projects in the recent years in Linux with the LSP Plugins as my main choice. Normally I also run FL Studio in the same Linux Reaper Projects with WINE for generation Sounds (I just really like their Piano Roll and Synths). This has worked fine, until we needed to create some Live Lyrics. FL Studio has a Lyrics Plugin with their ZGameEditorViszualizer, but it always crashes when trying to switch Projects or Close (with WINE). So we had no choice but to switch to Windows... (were using a special Band PC for Live-Gigs) But now all my old Projects are still using LSP Plugins and I can't load them on there... I tried building them from Source in a VM (the compiler gave absolutely no errors after I have installed the Microsoft Visual C++ Runtime, which PHP needs), but the Plugins just fails to load in Reaper after I have copied them over to the PC. If I try to load it in Carla it shows the Error "Failed to load file"; "Failed to get plugin description" I simply followed the build guide step by step.

What did I do wrong?

Really really hope somebody can help out here...

**Comment by sadko4u** [comment]
Hello! I don't see any problems with LSP Plugins and REAPER for Windows. Need more detailed information about what you're doing and what format of plugins do you use. There can be different reasons and multiple problems.

**Comment by ReComplexed** [comment]
Hi,
I am simply trying to port my old projects over to Windows, and none of the Plugins work, like I described. All if them... Maybe I built it wrong?

**Comment by ReComplexed** [comment]
After the Plugins have been Built, I have copied the "INSTALL" Folder to another Computer. Then I copied the Folders inside "lib" to their Locations. Is maybe something wrong there?

**Comment by sadko4u** [comment]
We need to understand:
1. What plugin format you're trying to build. There are LADSPA, LV2, VST2, VST3 and CLAP available to build for Windows.
2. What is the actual result of building the plugins. How do you install them, where do you place them, etc. Note that `make install` does not install plugins into Windows system directories. Instead of this, it installs them into `INSTALL` subfolder.
3. There can be some system dependencies that are missing on a target machine. Have you tried to launch your builds directly in the VM?
4. You can upload your build binaries somewhere to make me possible to check them.

**Comment by ReComplexed** [comment]
Hi,
thanks for clarifying.
1. I am trying to install All Versions that are supported by Reaper (everything).
2. The Build shows no errors at all. Yes, I copied the files to the System Folders
3. Yes, this seems to be happening. The Build runs perfectly inside my build VM. I have found out that I also have to install mingw64 on the target Machine and add it to the path as well, which seems strange to me, but oh well. It works now.

Is part of the PHP Binary also needed at runtime?

Thanks for the quick reply!

**Comment by sadko4u** [comment]
I've just did the following:
1. Has built LSP Plugins under Windows 8.1 64-bit with GCC in virtualbox.
2. Archived the INSTALL directory and copied to a machine with Windows 10 installation without any GCC/GNU toolchain.
3. Moved folders to proper locations like `С:\Program Files\Common Files\VST3`, `С:\Program Files\Steinberg\VSTPlugins`, etc.
4. Launched REAPER and scanned for plugins.

What I can conclude.
At least they launch:
![изображение](https://github.com/user-attachments/assets/e11e4527-d4a7-4e84-97e4-49ba736d9734)

The only problem I meet is that plugins are drawing improperly: it seems that normal 100% UI scaling is overridden by the host with 125% and forcing it being back 100% doesn't completely fix the problem: controls are drawn in one place but  their bound boxes for actions are located in another places.

**Comment by ReComplexed** [comment]
For some reason I also needed the mingw64 Folder, but that's ok. It's more important to me that my old Projects load. The UI Drawing is also not the biggest problem, because I still make the majority of my Work in Linux, where everything works without any Problems. It just needs to "work" in Windows at Live-Gigs.

Thanks again so much for your quick help!

**Comment by ReComplexed** [comment]
Wait... I am actually not having any UI issues like you described... It's all basically like in Linux... It's not at 125%, and there are no bugs!

**Comment by sadko4u** [comment]
Nice, but I have. It seems that Windows system scaling set up to 125% on my laptop breaks the UI behaviour. In your case it seems that scaling is just 100% and that's why you're not meeting such issue.

**Comment by sadko4u** [comment]
> For some reason I also needed the mingw64 Folder

The reason can be that you used improper GCC installation that, for example, uses POSIX threads and requires some MinGW runtime to launch the libraries. Use of MinGW with native Windows threads installation should fix the problem.
