### ISSUE TITLE
UI scaling and window size

### ISSUE THREAD

**Issue by sadko4u** [lsp-plugins/lsp-plugins#418]
While investigating the issue #417 another problem occurred: in Windows 10 + Reaper environment the UI scaling of 125% makes plugin windows render improperly: windows are over-sized.

**Comment by ReComplexed** [comment]
This is what it looks like for me, everything is defaulted to 100% scaling:

![Screenshot](https://github.com/user-attachments/assets/a335478e-9406-4fc8-9bc6-826ae478a27e)

It's somehow not so cut-off like in your screenshot.

**Comment by sadko4u** [comment]
The problem was in Direct2D rendering backend: it took system DPI instead of using default DPI of value 96.
Removed taking system DPI, and now it works without any problems.

Related commit:
https://github.com/lsp-plugins/lsp-ws-lib/commit/ab11d48de0f63bbc7bf7af54ed0c1a0c9db72f85
