### ISSUE TITLE
Impulse Responses - Add ability to reverse impulses

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#419]
ENHANCEMENT
I noticed that the Impulse Responses plugins do not contain the ability to reverse impulse responses like the Impulse Reverb plugins do.
Might be nice to add to these plugins as well, unless there is a reason I am unaware of.
If added can also make the waveform visually show up as reversed when enabled, exactly how the Impulse Reverb plugin does.

Thank You

**Comment by audio2000** [comment]
I had original assumed that the Impulse Reverb was different / would use more resources because it  contained 4 slots then the Impulse Responses plugin, so I was planning on using the Impulse Responses plugin.

With a little testing they appear to be the same except that the Responses plugin offers Sources: None,Left,Right and the Impulse Reverb offers Sources: File 1 2 3 4.
I do not entirely know what this means yet but does anyone know if the Impulse Reverb plugin can also access None,Left,Right sources like the Responses plugin offers?
Also the its seems that the Impulse Reverb plugin also uses the same amount of DSP as the Responses plugin when only loading one IR file.

Anyways reason I am mentioning all of this is that as long as the Impulse Reverb plugin can do everything the Responses plugin can do, I can just use that one instead because it already contains the requested "Reverse" feature I mentioned in this post to be added to the Responses plugin.

If okay, I will leave this post open for a little while to see if I get confirmation for my assumptions, but I will close it soon.

**Comment by sadko4u** [comment]
You can load multiple files and get the "True Reverb Effect" by applying a trivial effect in Impulse Reverb plugin. Please read the manual carefully:
https://lsp-plug.in/?page=manuals&section=impulse_reverb_stereo

BTW having an abilty to reverse the impulse in Impulse Responses could be a good feature.

**Comment by audio2000** [comment]
Thank you for your response.
No I agree that was why I asked for it originally, I just didn't know if you guys wanted to add it.
I will keep this post open.
Thank you again

**Comment by sadko4u** [comment]
Just pushed the changes, will be available in the upcoming release.

**Comment by sadko4u** [comment]
Available in 1.2.18.

**Comment by audio2000** [comment]
Was able to test, works great thank you for adding this.
