### ISSUE TITLE
Add Next and Previous arrows to plugins that load audio files

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#420]
ENHANCEMENT:
Main plugins I think would benefit from this are Impulse Responses & Impulse Reverb but could also be useful in sampler plugins as well.
Add Next and Previous arrows to the GUI that load up the Next or Previous sample located in the folder that the current audio sample is loaded from.
So if had the following audio files in a folder
1.wav
2.wav
3.wav

If you had 2.wav loaded into a plugin, the PREVIOUS arrow would load 1.wav and the NEXT would load 3.wav

Hopefully others will find this idea useful
Thank You

**Comment by sadko4u** [comment]
This is not trivial according to current solution. For the plugin, the audio file is just a path to some file. For some plugin formats it is not an absolute path, but the virtual path. For example, in LV2 we have the [LV2:mapPath](https://lv2plug.in/ns/ext/state#mapPath). That means that each plugin that saves it's state should call `mapPath` to the path it uses.
From the host side, it can behave differently. For example, it can copy the original file to the project and return path to it. So after we load the session in the DAW, we lose any contact with the original file and it's location.
Maybe another solution could be to store the path the file was originally loaded inside of the plugin and do not use mapPath for that. But that gives additional questions:
- How the next/previous file should be selected? Should we perform the alphabetical sort of files?

**Comment by audio2000** [comment]
@sadko4u 
Thank you for responding.  I apologize I didn't know about all of this when requesting.  
If the solution you came up with would work, this could be good.  
I think going alphabetical order makes sense, I think this is probably standard sorting people would use in the folders themselves, so the next/prev arrows would mimic this order.
Not important, but if possible might also be nice that when the next/prev arrows get to the top or bottom of the file list, they stop, they do not cycle back to the top or bottom of the file list.

Not sure if anyone else agrees but I think if this could be added it could be very useful.
IR packs available usually contain many different files in various folders, no way of really knowing what every single one of them is without hearing them.  This would allow user the ability to cycle through them as audio is going through the plugin / IR to hear how they sound in realtime.

Thank you again

**Comment by tinglycraniumplacidly** [comment]
would also love for this to be a part of the Sampler plugins! alphabetical would be fine as @audio2000 mentioned

**Comment by sadko4u** [comment]
We got a working prototype. @bor-T will port controls to all plugins that use loaded samples and will polish the UI.

**Comment by sadko4u** [comment]
Buttons and even more are available in 1.2.18.

**Comment by tinglycraniumplacidly** [comment]
love the "random" feature, thank you!!

**Comment by audio2000** [comment]
I didn't realize this was in the previous milestone, from the sound of it it did not sound like this was going to be possible, thank you for adding this, glad it worked out.
I have some ideas to share about this new approach if interested, I will make some new posts.
