### ISSUE TITLE
Setting to use number 1 instead of 0 for items in GUI

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#421]
I noticed that these plugins use 0 instead of the number 1 to start off item lists.
For example in the sampler plugins you see 0-7 for samples instead of 1-8.
Can also be seen in EQ plugins as well.
Not sure if anyone else would agree, I know this is common in computing approach, but this has always been confusing to me.
Maybe can add a setting that can change this visually in all GUIs that contain this approach?

Again not sure if others would agree/find this useful
Thank You

**Comment by audio2000** [comment]
Thank you for adding this to the milestone.
I didn't think anyone would care about this, thank you.
You guys probably already know which ones have this, I mentioned the....
-Samplers / Multi-Samplers
-EQs
-Impulse Reverb (just noticed this one as well)

Thanks again

**Comment by sadko4u** [comment]
Seems that @bor-T has completed all the job with renaming.
Please not that it will only affect the UI, for backward-compatibility reason we don't rename parameters nor inputs/outputs.

**Comment by sadko4u** [comment]
Done in 1.2.18.

**Comment by audio2000** [comment]
Tested, works/looks great.
I did not see a way to change back to using 0s, so am I correct that this was just a decision that was decided to be the default as instead of a setting?

**Comment by sadko4u** [comment]
Yes, we just changed the numbering in the UI.

**Comment by audio2000** [comment]
Ah okay I just wanted to make sure I was not overlooking a setting to test, thank you guys again for making this update.
