### ISSUE TITLE
[Windows 11] Child windows fight for priority

### ISSUE THREAD

**Issue by ShadowShok** [lsp-plugins/lsp-plugins#426]
This makes the context menu flicker when it opens on a child window.

https://github.com/user-attachments/assets/08a91c9f-5c0a-4086-a4ce-cb4f0725afe3

**Comment by sadko4u** [comment]
This is definitely bug and need to be solved in the nearest release.

**Comment by sadko4u** [comment]
Made some changes. Should be fixed in the upcoming release.

**Comment by sadko4u** [comment]
Fixed in 1.2.18.
