### ISSUE TITLE
build instructions on windows unclear

### ISSUE THREAD

**Issue by yankscally** [lsp-plugins/lsp-plugins#429]
getting a lot of errors trying to `make` lsp for windows. Would really appreciate some binaries for windows if possible! FL studio is now supporting CLAP as of FL24.

https://lsp-plug.in/?page=download&section=source

i followed the instructions here and get some errors.

```
 g++  [lsp-plugin-fw] wrap/clap.cpp
wrap/clap.cpp: In function ‘void lsp::clap::gen_descriptors()’:
wrap/clap.cpp:758:25: error: ‘asprintf’ was not declared in this scope; did you mean ‘vsprintf’?
  758 |                     if (asprintf(&tmp, "%d.%d.%d",
      |                         ^~~~~~~~
      |                         vsprintf
wrap/clap.cpp:766:29: error: ‘asprintf’ was not declared in this scope; did you mean ‘vsprintf’?
  766 |                         if (asprintf(&tmp, "%s CLAP", manifest->brand) >= 0)
      |                             ^~~~~~~~
      |                             vsprintf
wrap/clap.cpp:769:29: error: ‘asprintf’ was not declared in this scope; did you mean ‘vsprintf’?
  769 |                         if (asprintf(&tmp, "%s/doc/%s/html/plugins/%s.html", manifest->site, "lsp-plugins", meta->uid) >= 0)
      |                             ^~~~~~~~
      |                             vsprintf
make[3]: *** [Makefile:1106: /c/Users/micro/Desktop/lsp-plugins-src-1.2.17/.build/target/lsp-plugin-fw/wrap/clap.o] Error 1
make[3]: Leaving directory '/c/Users/micro/Desktop/lsp-plugins-src-1.2.17/modules/lsp-plugin-fw/src'
make[2]: *** [Makefile:67: all] Error 2
make[2]: Leaving directory '/c/Users/micro/Desktop/lsp-plugins-src-1.2.17/modules/lsp-plugin-fw'
make[1]: *** [Makefile:145: all] Error 2
make[1]: Leaving directory '/c/Users/micro/Desktop/lsp-plugins-src-1.2.17/src'
make: *** [Makefile:68: all] Error 2
```

**Comment by sadko4u** [comment]
Hello!

For Windows, `asprintf` function is defined in the `<lsp-plug.in/stdlib/stdio.h>` file.
Need more details.  Please post your build log with `VERBOSE=1` make option.

**Comment by yankscally** [comment]
hey there. I'm probably not going to be much help as I'm not that great at building cpp projects, but I would love to show you this clap tracker list i have been working on with a friend with the help of https://clapdb.tech :

https://docs.google.com/spreadsheets/d/1FkKeoTAXZt4ZvUPYOkNSZMVR5xHu6mX2GIIUpZvAOII/edit?usp=sharing

basically, we are using a software called Blockhead, and it has just supported CLAP, so we have been testing what works on it. it also has some extra info about licensing and if its free/needs signup. This is just a copy because of google editor permissions, can send you the live one when we have finished editing it!

Unfortunately I won't be able to check LSP off the list for windows (I use windows) or I guess macOS, but I'd really love to.. I've been dying to try out LSP plugins, but I am not able to get a windows build because I'm not good at the building part.

Is a windows .clap build within the realm of possiblity?

**Comment by sadko4u** [comment]
Closing the issue as there is nothing to do.
