### ISSUE TITLE
Sampler stretch tab changes the width of GUI

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#432]
Linux based Sampler based plugins
Not sure if this happens to everyone or if this is specific to some kind display setting.

I noticed that ironically, the "Stretch" tab found in the "Sampler" plugins, ends up stretching/changing the width of the plugins GUI window when you click on this tab.
I believe this is because the "Stretch" tabs parameters require more width than the parameters in all the other tabs, so when you click on this tab the plugin GUI window adjusts its width to fit these parameters.
This causes a strange unexpected kind of movement as the plugin adjusts its width from the center and then adjusts back if you click on any of the other tabs.

When clicking on the "Stretch" tab, this width change also causes the right edge of the plugins window to cut off half of the "Sample 7" velocity layers vertical parameter strip.  When you click back on any of the other tabs, the plugin GUI window adjusts back but this right edge issue remains.
You have to adjust the plugins width manually OR close the GUI and open it again to correct this.

In order to correct this (if feel that it is worth correcting), I would imagine the Stretch parameter section width needs to be narrowed to match all the other tabs, but if cannot fit the parameters to that size, then all the other tabs parameter section widths would have to be increased to the same size as the "Stretch" sections.

Hopefully this makes sense how I am describing it.
Does anyone else experience this GUI width issue?
Thank You

**Comment by sadko4u** [comment]
It seems that the problem occurs when the font scaling is set greater than 100%.

**Comment by sadko4u** [comment]
Added aggregate size computation for TabControl widget.
Now changing font size does not cause the described problem.

**Comment by audio2000** [comment]
Thank you for fixing this.
I do not know the procedure for this pending label so I will just keep this open until you decide to close it.
Thank you again

**Comment by sadko4u** [comment]
I'll close all solved issues when the release will be published.

**Comment by sadko4u** [comment]
Fixed in 1.2.18.

**Comment by audio2000** [comment]
Tested, works great, thank you
