### ISSUE TITLE
Spectrum analyzer gain values.

### ISSUE THREAD

**Issue by sergionexus** [lsp-plugins/lsp-plugins#434]
When using LSP Spectrum analyzer, gain values of the different frequencies are not the same as the values showed by other metering plugins like T-Racks Metering for example.

**Comment by sergionexus** [comment]
> Hello! And?

And I can't trust it if all the other metering plugins give other values. I don't know if it's a bug, but the fact it's that this plugin gives wrong values.

**Comment by sadko4u** [comment]
The gain value is a relative value and has a sense when you compare it to some other gain value. Have you compared the results given by other plugins respective to yours reference one?

**Comment by sergionexus** [comment]
> The gain value is a relative value and has a sense when you compare it to some other gain value. Have you compared the results given by other plugins respective to yours reference one?

I did It. I tried 4 metering plugins apart of this one, and with the same sound in the same point (about 190 Hz), all the other plugins give values of 12~14 and LSP gives ~34.

**Comment by sadko4u** [comment]
Added +12 dB compensation on measurement. Two pure sine waves at 0 dB amplitude at the input of plugin.
![изображение](https://github.com/user-attachments/assets/22afec8c-1a0f-4908-b212-4e68a342bdef)

**Comment by sergionexus** [comment]
My reference plugin is T- Racks. This is the info in the T-Racks Manual:

•FTT Size: the filter size can be 2048, 4096, 8192, 16384 and 32764 samples. 

•FTT Overlap: the overlap speed can be at 2x, 4x, 8x or 16x. 

•FTT Window: the Window can be Hann, Hamming, Blackman-Harris, Flat Top style or no window.

•Filter Size: the filter size can be 1, 1/3, 1/6 or 1/9 of octave. 

•Channel mode: select between L, R and L+R. 

•Range: the ranges of vertical scale of the RTA can be set in -130…+5, -90…0 or -60…0. 

•Release: set the release time of the meter between 250ms, 500ms and 1sec. 

•Peak Hold time: it is possible to visualise the peak in the spectrum and here you can select for how long.

**Comment by sadko4u** [comment]
Available in 1.2.18.
