### ISSUE TITLE
Mono Sample in Stereo Sampler Plays in Left Channel Only

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [lsp-plugins/lsp-plugins#436]
When I load a mono sample into any of the Stereo Sampler or Multi-Samplers, the default output is only through the left channel. I would strongly prefer it to play in both channels by default.

![image](https://github.com/user-attachments/assets/e4ba9c92-1016-40bb-a387-54c38975cb30)

I use the Sampler plugins in Ardour. My current workaround is to route the L of the Sampler plugin to both the L+R of the Ardour audio track. It's annoying to have to do this for ever mono sample I use. The only other workaround I've found is the bring the Pan Left to 0, but that's even more difficult to get right with a mouse and no detent.

Thanks! Love these plugins btw!

**Comment by sadko4u** [comment]
> The only other workaround I've found is the bring the Pan Left to 0, but that's even more difficult to get right with a mouse and no detent.

You always can double-click the value under the knob and enter the desired value manually.
https://lsp-plug.in/?page=manuals&section=controls

**Comment by tinglycraniumplacidly** [comment]
thanks for the tip. that certainly helps. i still think it should be by default since this is how other samplers work.

**Comment by sadko4u** [comment]
In the upcoming release mono samples will be played as stereo samples with duplicated left channel. This will solve your problem but break panning for those who used mono samples previously.

**Comment by tinglycraniumplacidly** [comment]
sick, ty!

**Comment by sadko4u** [comment]
Available in 1.2.18.
