### ISSUE TITLE
Add Instrument names to Instrument drop down

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#437]
Linux

Might be helpful to add the "Instrument" "Name" in the drop down menus
`Instrument 0`
`Instrument 1`
could be something like
`Instrument 0:  Kick`
`Instrument 1:  Snare`
This could make it easier for user to find the "Instrument" they are looking for from the list

May not be desired but just an idea, because Multi-Sampler plugins offer double digit amounts of "Instrument"s maybe could add a 0 padding to single numbers which would then make all names aligned
`Instrument 00:  Kick`
`Instrument 01:  Snare`  ......
`Instrument 10:  Cymbal`
`Instrument 11:  Hihat`

Not sure if anyone would find this useful?
Thank You

**Comment by audio2000** [comment]
The following is not important / I think it is probably too late to change the terminology anyways but the use of "Instrument" in this context can be slightly confusing.  I find it tricky to even make posts containing this term because it could be viewed as a different meaning.
I honestly cannot think of a better name either, I was thinking "Note" because they can be viewed as "Notes" and then "Sample" can be viewed as velocity layers / layers of those "Notes" but "Note" might also be confusing as well? not sure.  Maybe can use something like "Slot"?  The naming for this is tricky.
Would have the benefit of eliminating a little confusion if any other users view this as confusing.
Anyways another reason why I am mentioning this here is that a shorter name could also benefit the suggestion above because now the names will/could be longer.
Again might not be worth it / too late to do this anyways.

Thank You

**Comment by sadko4u** [comment]
Changing instrument name can be a bit tricky since combo boxes display metadata only. I need to think of how to implement this feature.

**Comment by sadko4u** [comment]
Still seems to be possible:
![изображение](https://github.com/user-attachments/assets/a4d87416-c889-42b6-ae9b-e4ceef86bc2c)

**Comment by audio2000** [comment]
Wow thank you for adding/working on many of my suggestions good to see that they are worth adding.
You do not have to add them, up to you, sometimes I like them sometimes I do not as well as far as adding the "0" padding to 0-9. Only reason I say this in this case is that adding them may allow everything in the list to be aligned nicely.
Now that you have a working version that can display these labels, if you have some time maybe can test and see if it looks weird with or without the 0 padding, when you add label names beyond "Instrument 9:"

Also I was wondering how the name lengths would be handled.....
Does the menu width adjust to accomodate for longer name lengths?
Is there a maximum number of characters a name can include?
If there is a maximum, do the names truncate?

Anyways, looks great, I think this will be very useful, hopefully other users agree.
Thank you again for adding this.

**Comment by sadko4u** [comment]
> Does the menu width adjust to accomodate for longer name lengths?

Yes, the dropdown menu computes the maximum length of the list box item and uses it for the size of the popup window.

> Is there a maximum number of characters a name can include?

Theoretically there is no limitation.

> If there is a maximum, do the names truncate?

No, we don't truncate names at this moment.

**Comment by audio2000** [comment]
Ahh I was making little edits to my post, didn't realize you had already responded below :)
I will move it to this post, I was just mentioning, wonder if there would be a benefit of adding a space or two after the ":"s in general to separate the "Instrument #:" label from the "names".
Again obviously all of this is up to you, hopefully I am not bothering you,  just figured I would discuss while release is pending.
Just fun to be able to discuss/think of little tweaks before releases occur.

That is good to hear that the menu can adjust its width based on the names, I like this.
Also like that it will show full names, so many applications make everything with limited truncated names cannot read anything :)

Again thank you for responding and for making these updates to your plugins, hopefully other users will find some of these updates helpful as well.

**Comment by sadko4u** [comment]
> I will move it to this post, I was just mentioning, wonder if there would be a benefit of adding a space or two after the ":"s in general to separate the "Instrument #:" label from the "names".

It won't make sense because we're using fonts with non-constant glyph width. If we add some spaces, it won't compensate the spacing for instruments with numbers higher than 10.

> That is good to hear that the menu can adjust its width based on the names, I like this.

This is how the [lsp-tk-lib](https://github.com/lsp-plugins/lsp-tk-lib) is designed.

**Comment by sadko4u** [comment]
Available in 1.2.18.
