### ISSUE TITLE
Multi-Sampler X48 Instrument drop down - Vertical scroll bar covers numbers

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#438]
Linux

I noticed a few issues with Multi-Sampler X48 specifically.
This is due to it having a slightly different "Instrument" drop down than the other Multi-Sampler plugins.

This X48 drop down contains a vertical scroll bar which ends up covering up the double digit numbers.
(Not sure if this is a font setting on or if all users experience this issue?)
Probably not worth doing as mentioned in the following post #437 but in the reply I made to this post mentions the changing/shortening of the "Instrument" name.  Which could fix this issue at the same time.
Anyways if not then maybe could widen the drop down a little in the X48 to fit these numbers (depends if the other Multi-Sampler plugins all use the same drop down code?)

Hope this helps
Thank You

**Comment by sadko4u** [comment]
Horizontal scroll bar should not be used for drop-down lists. Fixed this in latest commit.

**Comment by audio2000** [comment]
I apologize I meant to say "vertical" scroll bar not "horizontal"
I have made the appropriate edits to my post.
It is the "vertical" scrollbar that shows up on the right side of the menus that ends up on top of the  numbers currently.

Cannot test myself because I do not have a pending release versions to test but if anyone has some time, can verify that the following #437 update, that adds the ability to show "Instrument" names in the drop down menu, does not conflict with this "vertical" scroll bar either.

Hope this helps
Thank You

**Comment by sadko4u** [comment]
Fixed in 1.2.18.
