### ISSUE TITLE
Multi-Sampler X48 Instrument drop down - Mouse scroll wheel slow

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#439]
Linux

I noticed a few issues with Multi-Sampler X48 specifically.
This is due to it having a slightly different "Instrument" drop down than the other Multi-Sampler plugins.

If you use your mouse scroll wheel to scroll up/down in the "Instrument" drop down it seems very slow.
It appears that mouse scroll wheel setting might be set to very small increments?
Maybe can increase?

Hope this helps
Thank You

**Comment by sadko4u** [comment]
Improved the behaviour of drop-down lists.

**Comment by sadko4u** [comment]
Fixed in 1.2.18.
