### ISSUE TITLE
Unable to load plugins via Pedalboard

### ISSUE THREAD

**Issue by duringleaves** [lsp-plugins/lsp-plugins#444]
I'm trying to use the LSP effects suite as part of an automated Python environment using Pedalboard, but so far, I haven't cracked the code to loading it correctly.

Error loading plugin lsp-plugins.vst3: Failed to load plugin as VST3Plugin. Errors were:
	VST3Plugin: Unable to scan plugin /home/ec2-user/.vst3/lsp-plugins.vst3: unsupported plugin format or scan failure.

Has anyone else had any luck invoking the effects in this way?

**Comment by sadko4u** [comment]
Hello. What's Pedalboard?
What operating system do you use?

**Comment by duringleaves** [comment]
Pedalboard <https://github.com/spotify/pedalboard> is Spotify's Python audio effects library for Linux.  In addition to its own native plugins and DSP, it supports Linux VST3's.  I've had no troubles with other plugins like Blindfold EQ or WSTD EQ.  Right now, I'm running these scripts on an AWS Amazon Linux 2023 instance.

Because lsp-plugins.vst3 looks like it might be a wrapper around the individual effects, I'm wondering if that's the roadblock to using it in this manner.

**Comment by sadko4u** [comment]
Have you checked the proper work of plugins in other hosts like REAPER or Ardour?

**Comment by duringleaves** [comment]
Unfortunately, it's not an apples to apples comparison since those are both DAWs that invoke the GUI and I'm trying to access the effects programmatically.  I was hoping to just find a little more information or previous experience before I spend too much time debugging, in case it simply isn't possible with this suite.  I'll share whatever I find back to this thread in case it helps others.  Thanks!

**Comment by sadko4u** [comment]
You're understanding question wrong. If you have problems with installation of plugins, then no DAW will see them.
If plugins work properly in DAW, then it is reason to check why they don't work in Pedalboard.
There also can be binary dependencies unsatisfied. Have you tried to perform `ldd` on the shared object file of plugins stored inside of the `lsp-plugins.vst` path?
It is also useful to have a try to build plugins with `TRACE=1` option to check their logs. Maybe something interesting can be found there.

**Comment by duringleaves** [comment]
Thank you!  You were absolutely right.  _ldd_ exposed librandxr dependency was missing!  I'm now seeing the list of internal plugins!  Thanks for hanging in there with me.  :)

**Comment by sadko4u** [comment]
Nice to see that the probem has been solved.
