### ISSUE TITLE
Make number labels buttons in all sampler plugins

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#445]
As mentioned for me I would need a sampler that contains a volume envelope, so currently I am just mentioning these suggestions for the sampler plugins because I feel that some of them could be useful to other users, I hope this is okay to continue to mention some ideas.

I thought it might be helpful to be able to turn the "Sample" number labels 1-8 into square or rectangular buttons.  Clicking on these buttons would then show that sample layers waveform (if it has a sample loaded into that slot) in the waveform view, mimicing selecting Sample from the drop down list.

Button could have a subtle outline highlight to indicate that is the current sample loaded.
This highlight would also update when use the drop down menu.

Not sure if any other users would find this useful.

Thank You

**Comment by sadko4u** [comment]
I think we can replace combo group with tabs but that requires to implement new widget which will show tabs but work similar to combo group wiget.
@bor-T what do you think?

**Comment by sadko4u** [comment]
Here's a new look with tabs instead of combo:
![изображение](https://github.com/user-attachments/assets/985a63f6-cbd4-4e76-af53-0c7df746acb2)

**Comment by sadko4u** [comment]
Available in 1.2.20!

**Comment by audio2000** [comment]
Nice, thank you for adding this
