### ISSUE TITLE
Please return  lsp-plugins-src-1.2.18.tar.gz to release assets 

### ISSUE THREAD

**Issue by Vascom** [lsp-plugins/lsp-plugins#447]
Please return tar.gz sources for direct download. I need it for creating rpm package for Fedora.

**Comment by sadko4u** [comment]
Hello! It is. But now packaged into 7z archive: https://github.com/lsp-plugins/lsp-plugins/releases/download/1.2.18/lsp-plugins-src-1.2.18.7z

**Comment by Vascom** [comment]
7z is not trivial for unpackaging during rpm build.

**Comment by sadko4u** [comment]
What's the problem? The 7zip archiver is missing?

**Comment by sadko4u** [comment]
I've looked to OpenSUSE RPM build service, and they handle 7z files pretty well:

https://build.opensuse.org/projects/multimedia:apps/packages/lsp-plugins/files/lsp-plugins.spec?expand=1

I think this spec file can be a good reference.

**Comment by sadko4u** [comment]
Returned back GZip tarballs for source code releases. Available in 1.2.19.
