### ISSUE TITLE
GUI fails to load for CLAP versions of 1.2.18

### ISSUE THREAD

**Issue by Olnium** [lsp-plugins/lsp-plugins#448]
CLAP versions of plugins from v1.2.18 initially crash on load, then load when reloaded in DAW, but fail to open GUI. VST3 works as expected.

Built with MINGW64
Build platform: Win 11 Pro
Build target: Win-x64
DAW: Bitwig 5.2.4 (CLAP api 1.2.1)

**Comment by sadko4u** [comment]
Are the previous versions (at least 1.2.17) working under these conditions?
Have you tried another DAW? Does the problem persist there?

**Comment by Olnium** [comment]
I'm unable to comment on v1.2.17.
Regarding alternative DAWs, I tried Reaper and FL Studio, and CLAP GUIs load in both so it would appear to be a Bitwig specific issue. Within Bitwig, I tried all 3 available graphics backends (Direct3D, Vulkan, and OpenGL) and the issue persists.

I should mention that I have an iGPU (Ryzen 5600G).

**Comment by sadko4u** [comment]
Yes, it seems to be a Bitwig issue then. I'll look at it more precise.

**Comment by sadko4u** [comment]
OMG, my Windows 8.1 virtual machine is too old for your version of Bitwig. I'll try to reproduce problem with older Bitwig versions.

**Comment by Olnium** [comment]
Bear in mind that only versions above v5.2 of Bitwig have the new hardware accelerated graphics backend, which may be a contributing factor. They also introduced a requirement for a SSE 4.1 capable CPU a few minor versions ago.

**Comment by sadko4u** [comment]
No, the problem was in infinite recursive window sizing when showing the window. Fixed it.

**Comment by sadko4u** [comment]
Fixed in 1.2.19

**Comment by Olnium** [comment]
Confirmed fixed. Thanks!
