### ISSUE TITLE
1.2.19: VST3 not appearing with its GUI

### ISSUE THREAD

**Issue by talbym** [lsp-plugins/lsp-plugins#450]
lsp-plugins-1.2.19-Linux-x86_64.7z
VST3 is no more opening with its GUI but only the DAW provided interface appears. Was fully functional in 1.2.18.

**Comment by sadko4u** [comment]
Yes, can confirm. I found error in a release script. Please wait a while, I'll re-upload binaries soon.

**Comment by sadko4u** [comment]
Re-uploaded binaries. Now all should work just fine.
