### ISSUE TITLE
Plugin Latency is reported to the Host one step too late

### ISSUE THREAD

**Issue by whitespace-rebel** [lsp-plugins/lsp-plugins#453]
Hello everyone,

when changing Lookahead on the compressor or IIR to FIR (or vice versa) on the parametric eq, the current latency is reported to the host only if you push another button or rotate another knob on the plugin, or if you close the plugin window and reopen it again.

To better see it type in the lookahead value on the compressor plugin.

I hope it is reproducible in other hosts than mine.

My system:
Renoise 3.4.4
Debian 12 AMD64
Openbox window manager

Thank you!

**Comment by sadko4u** [comment]
Please don't forget the mention the plugin format you're trying to use. I suppose it's VST2 and VST3.

**Comment by sadko4u** [comment]
How did you manage that plugin is not reporting latency to the host?
I [added several log messages](https://github.com/lsp-plugins/lsp-plugin-fw/commit/115b10f52c9353a039828f98099f2848f0306979) and see in the debug log of Parametric Equalizer that plugin wrapper notifies the host about latency change when switching from IIR to FIR and back.
At least this happens in Ardour and it manages the latency change correctly.

**Comment by whitespace-rebel** [comment]
> Please don't forget the mention the plugin format you're trying to use. I suppose it's VST2 and VST3.

It was VST2 in Renoise.

I tested it in Ardour and it works correctly.


> How did you manage that plugin is not reporting latency to the host?

In Renoise you can click on the menu "Song -> Plugin Delay Compensation Info ...". It lists all the plugins that introduce latency (number of samples and milliseconds)

**Comment by sadko4u** [comment]
I suppose this is a problem of Renoise then.

**Comment by whitespace-rebel** [comment]
There are many plugins that work without issues when they need to report latency.
Some are problematic (mostly bridge plugins from LV2 to VST).
I'm ok if you want to close this issue.

**Comment by sadko4u** [comment]
I'll try to reproduce the problem with Renoise within few days.

**Comment by sadko4u** [comment]
Hello! Sorry for the delay. I've checked VST2 and VST3 plugins with Renoise. And I see that latency is properly reported by the equalizer. Don't know why Renoise doesn't sync latency immediately.
I suppose it being the upstream bug.

**Comment by whitespace-rebel** [comment]
It may also be a problem with Openbox not updating immediately. I will try another window manager.
Anyway, thanks for looking into it.

**Comment by emuell** [comment]
Hi Taktik from Renoise here. I've only tested the VST3 version of the LSP Parametric EQs here, and there seem to be two problems:

- the VST3 version does not report latency changes to the host at all (via restartComponent(kLatencyChanged)): See also https://forums.steinberg.net/t/reporting-latency-change/201601

- when polling for latency changes (we do so before starting playback for all plugins), the correct latency is reported *after* the plugin's first audio processing cycle finished. 

So Renoise will eventually get the correct latency, but the timing for the first playback in songs will be wonky. Latency changes in hosts are usually a disruptive thing that should not happen during playback - if possible.

**Comment by sadko4u** [comment]
Hello, @emuell!

> the VST3 version does not report latency changes to the host at all (via restartComponent(kLatencyChanged)): See also https://forums.steinberg.net/t/reporting-latency-change/201601

The plugin reports latency. If we build LSP Plugins with `TRACE=1` option, we will see in the log of the plugin:
```[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2624] process: Updating settings
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/controller.h: 553] notify: Plugin latency changed from 0 to 6144
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0xd1704f0, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1216] setActive: this=0xd1704f0, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1216] setActive: this=0xd1704f0, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0xd1704f0, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1745] getLatencySamples: this=0xd1704f0, latency=6144

```

This means that this code is running:
https://github.com/lsp-plugins/lsp-plugin-fw/blob/db40009aac0734b8b220b3de36bb56d2d76534fd/include/lsp-plug.in/plug-fw/wrap/vst3/impl/controller.h#L551-L557

Moreover, we return the latency to the host when the `getLatencySamples` is called. And this happens when no playback is started. So the assumption that LSP Plugins do not report latency is wrong.

> when polling for latency changes (we do so before starting playback for all plugins), the correct latency is reported after the plugin's first audio processing cycle finished.

This behavious is not correct. You need to react on each `restartComponent` call as soon as possible, not only when starting playback because plugin may change it's latency even on some automation change. I think this is the reason because Renoise does not behave same to other DAWs.

**Comment by emuell** [comment]
Not reporting at all maybe sounds a bit too mouthful. I haven't tested all possible cases. 

But in the attached Renoise Song it definitely does not report latency changes. So maybe there's some notification missing when restoring the plugin's internal parameter status.

[PDC_LSP.xrns.tar.gz](https://github.com/user-attachments/files/18251394/PDC_LSP.xrns.tar.gz)

The song only contains some LSP EQ VST3 instances.

To replicate, load the Song in Renoise. After loading, all LSP plugin instances report a latency of 0 samples. After playback started they start to report the correct latency, but only after Renoise manually polled the latency.

**Comment by sadko4u** [comment]
OK. Now I see. The host loads the session, instantiates plugins, reads their parameters but does not launch them. That means, that no `process` call is issued.  LSP Plugins detect parameter changes in the `process` call and update their internal latency there. The funny thing is, when I open the external editor, the `process` call is issued:
```
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8701750, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2009] toggle_ui_state: UI counter req=1, resp=0
[TRC][main/plug/Module.cpp:  53] activate_ui: UI has been activated
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: mode=1.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: send=3.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: return=3.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: ft_0=2.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: s_0=1.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: f_0=19.725170
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2624] process: Updating settings
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8502b30, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: mode=1.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: fsel=1.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: send=3.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: return=3.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: fltv_m=0.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: fts_0=2.000000
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2588] process: port changed: fs_0=75.229271
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:2624] process: Updating settings
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/ui_wrapper.h: 848] slot_ui_realized: sender = 0x7516810, ptr = 0x7ee0180, data = 0x7ffd72825710
[DBG][main/i18n/Dictionary.cpp: 100] load_dictionary: Trying to load file builtin://i18n/us/graph.json...
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/controller.h: 553] notify: Plugin latency changed from 0 to 6144
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/controller.h:1009] notify: Pushed new shared memory state
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:3545] transmit_shm_state: Submitted shm_state message
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/controller.h: 553] notify: Plugin latency changed from 0 to 6144
[DBG][main/i18n/Dictionary.cpp: 102] load_dictionary: Overall status = 0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8701750, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1216] setActive: this=0x8701750, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1216] setActive: this=0x8701750, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8701750, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1745] getLatencySamples: this=0x8701750, latency=6144
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8502b30, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1216] setActive: this=0x8502b30, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1216] setActive: this=0x8502b30, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8502b30, state=1
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1745] getLatencySamples: this=0x8502b30, latency=6144
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/ui_wrapper.h: 848] slot_ui_realized: sender = 0x7516810, ptr = 0x7ee0180, data = 0x7ffd728256d0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/ui_wrapper.h: 848] slot_ui_realized: sender = 0x7516810, ptr = 0x7ee0180, data = 0x7ffd72825710
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8701750, state=0
[TRC][/home/sadko/eclipse/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/wrap/vst3/impl/wrapper.h:1821] setProcessing: this=0x8502b30, state=0
```
According to the log we see that:
* when external UI is activated, `setProcessing` is called that triggers start of processing
* then plugin investigates that latency has changed and notifies the host
* then host issues `setProcessing` to stop processing and updates the latency by calling `getLatencySamples`
* then the host issues `setProcessing` to resume processing as usual
* then it stops processing again by issuing `setProcessing`.

I suppose it is not correct behaviour since controller is not always possible to detect the latency of the plugin. At this moment, Renoise enables processing when some parameter is changed, calls the processing and then disables the processing. This is very strange, especially when we're talking about generators, reverbs and delays which should work without stop in the host. Otherwise you'll get the reverb tail at the start of new playback because it is saved in the buffer of some plugin.

**Comment by sadko4u** [comment]
@emuell I've added a workaround:
https://github.com/lsp-plugins/lsp-plugin-fw/commit/e45ea5df2057e5e7e5518012725ecd776568bd21

But this still looks unnatural. You won't be able to report the latency for LV2 plugin format in such way. There, you are required to call [run](https://lv2plug.in/c/html/group__lv2core.html#a3cb9de627507db42e338384ab945660e) because the [pp::reportsLatency](https://lv2plug.in/ns/lv2core#reportsLatency) port is guaranteed to be [connected](https://lv2plug.in/c/html/group__lv2core.html#a4d904937a1bd27cb5f5478f95c708b16) only before the `run` call.

**Comment by emuell** [comment]
Thanks! We don't support LV2 plugins, so that should work fine. 

That plugins are suspended by default, when its inputs are silent, is an optional feature in Renoise. See Auto-Suspend at 
https://tutorials.renoise.com/wiki/Plugin#Plugin_Compatibility_Options

It's enabled by default for DSP FX only and usually works fine. In case it doesn't, it can be disabled.

**Comment by emuell** [comment]
Btw, that Renoise does not always run the plugin's process function, is not that uncommon. A few hosts do that as optimization. Ableton Live for example does that, I think Cubase too. 

Here getTailSamples https://steinbergmedia.github.io/vst3_doc/vstinterfaces/classSteinberg_1_1Vst_1_1IAudioProcessor.html#abb6b16a66b2356a4038a778b815dbbf3 is used by the host as a hint on how to check if the plugin needs to continue running after it got feed with some non silent input. We do check if the plugin produced an audible content for a while before shutting it down again.
