### ISSUE TITLE
Add ability to mute plugins that contain Listen button

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#455]
If decided to be added this can be done a few different ways to few different LSP plugins.
If developers / other users decide upon adding this / best approach I can make a new feature request for those ideas and close this post.

This request is to maybe add a mute/stop/panic to any plugins that contain a "Listen" button, basically plugins that play samples.
If sample lengths are long or very loud it could be nice to have a way to stop sound from being generated from them immediately when needed.

`PLUGINS`
Sampler (has Mute button)
Multi Sampler (has Mute button)
Impulse Response
Impulse Reverb

`IDEAS / DISCUSSION`
-If provided as a button could be nice to have in the same location as the "Listen" buttons but might kind of clutter up the GUI?
-Not sure if this would conflict with other programs and also how user would know but I kind of like the idea of maybe being able to click on the "Listen" button with Right Mouse Button to stop the sound.  If this is a conflict then I guess maybe could use Middle Mouse Button?
-The "Mute" buttons in the the Sampler plugins do work, but they are not close to the "Listen" button, because they are also for Muting the plugin when being played when receiving MIDI notes, but the RMB item mentioned above could be added to the Sampler plugins if this is agreed upon.
-The RMB item may also make sense for the Impulse Response loading plugins mentioned because it is not really that typical for user to be listening to IR sounds so having an actual button for this in the GUI may not really be necessary (the current Mute buttons in the Impulse Reverb are for a different purpose) so this is where the RMB can also serve a purpose.

Interested to hear what developers/users think.
Thank You

**Comment by sadko4u** [comment]
I think yes, adding a separate 'Stop' button would be a good option.

**Comment by sadko4u** [comment]
There are two more plugins:
- Trigger;
- Room Builder.

**Comment by sadko4u** [comment]
Available in 1.2.20!
