### ISSUE TITLE
Feature request: multiple maximum peak values

### ISSUE THREAD

**Issue by RattusSolarus** [lsp-plugins/lsp-plugins#457]
As per discussion at https://linuxmusicians.com/viewtopic.php?p=171379#p171379 , display of multiple peak values for Spectrum Analyzer x4 etc. would be a nice feature.
Maybe even an option for either maximum peak values, or averaged peak values so a short peak at a certain frequency would not overly influence the curve for a whole track.

**Comment by sadko4u** [comment]
Hi! Thanks for the ticket.

**Comment by RattusSolarus** [comment]
I had another though on this. If you want to implement the choice between maximum peak and average peak history, the history button could toggle between Off, Max Peak, and Avg Peak states, no need for extra buttons.

**Comment by sadko4u** [comment]
Available in 1.2.20!
