### ISSUE TITLE
Allow Enter key to apply the Save action in Save dialogs

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#458]
I noticed that when in any "Save" dialogs, when you type in name and hit your "Enter" key, it does not just apply the save and close the "Save" dialog, it requires user to go back to the mouse and click Okay.
 If it does not conflict with anything, feels like the "Enter" key should apply and close the dialog.
Not sure if anyone else agrees.

Thank You

**Comment by sadko4u** [comment]
Added when working on the issue #459. Works for both Load and Save dialogs

**Comment by sadko4u** [comment]
Available in 1.2.20!
