### ISSUE TITLE
Allow Escape key to close dialogs

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#459]
As long as there are no conflicts, I was wondering if the “Escape” key could be setup to close any dialogs that plugins open, such as the file picker, save as, about, etc.
Not sure if anyone else agrees.

Thank You

**Comment by sadko4u** [comment]
Added shortcut mechanics to the `tk::Window` class.
Added `Enter` and `Escape` key handling for dialog windows using this mechanics.

**Comment by sadko4u** [comment]
Available in 1.2.20!
