### ISSUE TITLE
Allow file pane to scroll with cursor in all browser based windows when using arrow keys

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#462]
Not sure if this is the best way to do this but I have noticed some things that occur in all browser based windows, so I will combine all in one post as the issue is the same.

-GUI based file browsers used in Samplers, Impulse Response loaders, etc.
-File Pickers
-Open
-Save As

A cursor/item highlight shows up in these file based browsers when they have focus and you use your up/down arrow keys. When this cursor reaches the edges at the top or bottom, if user keeps hitting up/down arrow, the cursor ends up going out of view. Suggesting if possible to mimic more of how a file manager functions, where when the cursor is at the top/bottom edge, hitting up/down arrows makes the file pane vertical scroll with the cursor so it is always visible to the user.

Thank You

**Comment by sadko4u** [comment]
Yes, indeed, automatic scroll when using keys should be a must.

**Comment by audio2000** [comment]
Thank you for confirming/agreeing.
I didn't mention something because I thought it would be covered by the arrow key fix, but just in case it is not, this would also apply to other keys such as PageUp/PageDown & Home/End as well.
Thank you again

**Comment by sadko4u** [comment]
That was definitely a bug which was introduced while fixing another issue. Just pushed the fix to the toolkit library.

**Comment by audio2000** [comment]
Thank you very much for working on this.
Okay so now this will be corrected in all the places it occurs in.

-GUI based file browsers used in Samplers, Impulse Response loaders, etc.
-File Pickers
-Open
-Save As

This is great, thank you again for fixing this

**Comment by sadko4u** [comment]
Available in 1.2.20!
