### ISSUE TITLE
Add mouse scroll stops to ends of Sampler plugin tabs

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#465]
In the Sampler based plugins you can mouse scroll on the tabs to cycle through them.
However it is currently programmed to cycle from end and restart over at the beginning and vice versa.
Being that there are not many tabs
Main / Pitch / Stretch / Loop
would it be considered to make the mouse scrolling to stop at the beginning and end and not cycle around again.

Thank You

**Comment by sadko4u** [comment]
Hello! And what's the problem? Why such behaviour is confusing?

**Comment by audio2000** [comment]
Sorry I had to step away for a minute.
I didn't say it was confusing, just thought that because not many tabs that having stops would be a little easier to control.
Just an idea, okay if do not agree.
Thanks for the response.
