### ISSUE TITLE
GUI File Browser - Allow items to auto load based on cursor highlight when navigating with keyboard

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#467]
When using computer keyboard to navigate, maybe can add a setting to allow the audio files to automatically load based on cursor highlight.
This way for example when using arrow up/down keys, each time they are hit which moves the cursor, the item they highlight get automatically loaded.
Currently the only way to do this is to have to keep clicking with mouse one at a time.

This could allow user to be able to use up/down arrows when MIDI or audio tracks are playing to test out different audio files.  For example, to test samples for sampler plugins or to test impulse responses while audio is playing.

Thank You

If the following idea post is added 468
EDIT: Sorry I meant to link #466 not 468.
When this setting is “on” the “bright highlight” (currently loaded item indicator) would move with the keyboard navigational keys.

**Comment by sadko4u** [comment]
Added the "Menu -> UI Behavior -> Automatically load files when navigating file list" option

**Comment by audio2000** [comment]
Wow thank you so much for adding this.
I apologize, I linked the wrong item in my original post, I meant to link 466 not 468, I have made the correction in my post above, sorry if any confusion.
Thanks again for working on this.

**Comment by sadko4u** [comment]
Available in 1.2.20!
