### ISSUE TITLE
GUI File Browser - Issue when using computer keyboard override in Ardour

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#470]
Possible Bug
lsp-plugins-1.2.19-Linux-x86_64

GUI file browser found in Sampler and IR based plugins.

`Steps To Reproduce:`
-In Ardour load up for example the Multi Sampler plugin
-Load a sample into the waveform pane so that GUI file browser is shown
-If the "keyboard" icon (in upper right hand corner of plugin window) that allows keyboard override is “off” (white)
-Using the up/down arrows on your keyboard moves the cursor up and down
-If the "keyboard" icon (in upper right hand corner of plugin window) that allows keyboard override is “on” (green)
-Using the up/down arrows on your keyboard moves the cursor up and down maybe once or twice but then stops being able to move the cursor.

There appears to be something wrong in general with plugin + Ardour keyboard icon, hard to narrow down.  
Here is a similar post that also happens #469

Thank You

**Comment by sadko4u** [comment]
Seems it has been fixed in #469

**Comment by sadko4u** [comment]
Fixed in 1.2.20!
