### ISSUE TITLE
GUI File Browser - Some navigational keys do not work when using computer keyboard override in Ardour

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#477]
lsp-plugins-1.2.20-Linux-x86_64
LV2
Ardour 8.10 Demo

GUI file browser found in Sampler and IR based plugins.

Thank you for making previous edits I mentioned about this.
Here are some new observations I noticed with the recent release of LSP plugins.

`Green Keyboard Icon OFF (Icon Is White)`
Arrow up/down = work as expected
Page up/down = work as expected
Home/End = do not work because Ardour uses these hotkeys to advance the play head in track editor which makes sense

`Green Keyboard Icon ON (Icon Is Green)`
Arrow up/down = do not appear to do anything (Possible Bug)
Page up/down = do not appear to do anything (Possible Bug)
Home/End = these two work as expected

I could not think of any other hotkeys to test other than these navigational ones, if there are any others you would like me to test out, please let me know.

Thank You

**Comment by sadko4u** [comment]
I can not do anything with key events because Ardour is intercrepting them and does not pass to the plugin's window. The only way is yes, setting the keyboard icon to green as it is designed in Ardour.
